### ISSUE TITLE
TextReport()

### ISSUE THREAD

**Issue by thasherwin** [selenide-examples/cucumber#2]
Does TextReport() works in Cucumber JUnit tests? I try adding it into my project but it did not work.. I don't see any logs. 

```
@Rule
  public TestRule report = new TextReport().onFailedTest(true).onSucceededTest(true);
```

Thanks!

**Comment by asolntsev** [comment]
@thasherwin Sorry for the long delay.

This question is more related to Cucumber than to Selenide. 
Looking at issue https://github.com/cucumber/cucumber-jvm/issues/393, I see that JUnit `@Rule` annotation is not supported by Cucumber. It means that you cannot use built-in `TextReport` rule with Cucumber, but you can create a very similar hook in Cucumber.

**Comment by thasherwin** [comment]
alright. thx for the update and no problem
