### ISSUE TITLE
Cucumber dataTable

### ISSUE THREAD

**Issue by breburdaTom** [selenide-examples/cucumber#8]
I would like to pass dataTables from scenarios to selenide methods in various ways. Sometimes for selection, sometimes for reading table results and doing an assertion if they are the same.

Would you please advise how to best approach this?

**Comment by asolntsev** [comment]
Hi @breburdaTom .
I think this question is rather about Cucumber than Selenide. I am not a Cucumber expert, you need to google it yourself. :)
