### ISSUE TITLE
TextReport support for Cucumber+TestNg

### ISSUE THREAD

**Issue by vrajasg** [selenide-examples/cucumber#9]
Hi,

Have just started to use Selenide and struck while configuring Text report. Can someone please clarify questions around Text report configuration?

     - Does Selenide support generating Text report when configured (or setup) with Cucumber+TestNg
     - Is slf4j mandatory as am already using log2j
     - Where can I see generated Text report, is it in the target folder

Really appreciate the support here as I couldn't found much help around the Text report setup. Also, apologies if this is not right place to post the question (please point me to right place if so). 

My Reference so far: https://selenide.org/documentation/reports.html

Thanks.

**Comment by rgone8x8** [comment]
@asolntsev thanks for the response, much appreciated.

Seems for some reason **text reports** are not generated when configured with Cucumber. 

So I took a step back and checked out [Selenide examples: Cucumber](https://github.com/selenide-examples/cucumber) project and even that didn't generate text reports. I see that project is already configured to generate a report (jUnit @Rule & slf4j-simple) as per [report doc](https://selenide.org/documentation/reports.html).

Here is the console output from my run, not sure what am missing here to see text report.
![Console output](https://user-images.githubusercontent.com/77437445/137317668-75cb83e7-d8b9-464a-9ca1-0fe014d9eae6.png)

### Steps followed:
 - In Intellij
 - Check out **_Selenide examples: Cucumber_**
 - Downloaded dependencies
 - Run _`mvn`_

Note: Also tried below

- By adding `cucumber.iml`
- Explicitly setting `onFailedTest` && `onSucceededTest` to **true** in `@Before` hook of Cucumber.

**Comment by asolntsev** [comment]
@vrajasg According to https://github.com/cucumber/cucumber-jvm/issues/393, Cucumber doesn't support JUnit annotatation `@Rule`. We cannot fix it in Selenide. :(

**Comment by asolntsev** [comment]
@vrajasg I have update the example project with an Cucumber-specific implementation of `TextReport`. Now it works with JUnit4 too.
